//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_AGRUPAMENTO_TIPOS_PRODUTO
    {
        public int ID_AGRUPAMENTO_ESTRUTURA { get; set; }
        public int ID_AGRUPAMENTO { get; set; }
        public int ID_TIPO_PRODUTO { get; set; }
    
        public virtual TB_AGRUPAMENTO_TIPO_PRODUTO TB_AGRUPAMENTO_TIPO_PRODUTO { get; set; }
        public virtual TB_TIPO_PRODUTO TB_TIPO_PRODUTO { get; set; }
    }
}
