//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLServerEntities : DbContext
    {
        public SQLServerEntities()
            : base("name=SQLServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RL_AGRUPAMENTO_TIPOS_PRODUTO> RL_AGRUPAMENTO_TIPOS_PRODUTO { get; set; }
        public DbSet<TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO> TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO { get; set; }
        public DbSet<TB_AGRUPAMENTO_TIPO_PRODUTO> TB_AGRUPAMENTO_TIPO_PRODUTO { get; set; }
        public DbSet<TB_APROVEITAMENTO_TRIAGEM> TB_APROVEITAMENTO_TRIAGEM { get; set; }
        public DbSet<TB_APROVEITAMENTO_TRIAGEM_ANALITICO> TB_APROVEITAMENTO_TRIAGEM_ANALITICO { get; set; }
        public DbSet<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS { get; set; }
        public DbSet<TB_DEPOSITO> TB_DEPOSITO { get; set; }
        public DbSet<TB_DEPOSITO_CD> TB_DEPOSITO_CD { get; set; }
        public DbSet<TB_ESTRUTURA_TIPO_PRODUTO> TB_ESTRUTURA_TIPO_PRODUTO { get; set; }
        public DbSet<TB_GRUPO_PRODUTO> TB_GRUPO_PRODUTO { get; set; }
        public DbSet<TB_LOG_ITEM> TB_LOG_ITEM { get; set; }
        public DbSet<TB_LOG_MASTER> TB_LOG_MASTER { get; set; }
        public DbSet<TB_PREVISAO_CONSUMO_PRODUCAO> TB_PREVISAO_CONSUMO_PRODUCAO { get; set; }
        public DbSet<TB_PRODUTO> TB_PRODUTO { get; set; }
        public DbSet<TB_PRODUTO_COMPATIVEL> TB_PRODUTO_COMPATIVEL { get; set; }
        public DbSet<TB_PROGRAMACAO_PRODUCAO> TB_PROGRAMACAO_PRODUCAO { get; set; }
        public DbSet<TB_PROGRAMACAO_RECEBIMENTO> TB_PROGRAMACAO_RECEBIMENTO { get; set; }
        public DbSet<TB_REL_ACOMPANHAMENTO_PRODUCAO> TB_REL_ACOMPANHAMENTO_PRODUCAO { get; set; }
        public DbSet<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS { get; set; }
        public DbSet<TB_REL_ENTRADA_INSUMOS> TB_REL_ENTRADA_INSUMOS { get; set; }
        public DbSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS { get; set; }
        public DbSet<TB_REL_GERENCIAL> TB_REL_GERENCIAL { get; set; }
        public DbSet<TB_REL_MOV_FORNEC_EXTERNO> TB_REL_MOV_FORNEC_EXTERNO { get; set; }
        public DbSet<TB_REL_PC_UTILIZACAO> TB_REL_PC_UTILIZACAO { get; set; }
        public DbSet<TB_REL_RPT_GARANTIA> TB_REL_RPT_GARANTIA { get; set; }
        public DbSet<TB_REL_SAIDA_INSUMOS> TB_REL_SAIDA_INSUMOS { get; set; }
        public DbSet<TB_REL_SAIDA_PRODUCAO> TB_REL_SAIDA_PRODUCAO { get; set; }
        public DbSet<TB_SALDO_ESTOQUE> TB_SALDO_ESTOQUE { get; set; }
        public DbSet<TB_SALDO_ETAPA_PROCESSO> TB_SALDO_ETAPA_PROCESSO { get; set; }
        public DbSet<TB_SEMAFORO_COBERTURA_ESTOQUE> TB_SEMAFORO_COBERTURA_ESTOQUE { get; set; }
        public DbSet<TB_SITUACAO_PRODUTO> TB_SITUACAO_PRODUTO { get; set; }
        public DbSet<TB_SUBGRUPO_PRODUTO> TB_SUBGRUPO_PRODUTO { get; set; }
        public DbSet<TB_TIPO_PRODUTO> TB_TIPO_PRODUTO { get; set; }
    }
}
