//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APROVEITAMENTO_TRIAGEM
    {
        public long ID_APROVEITAMENTO_TRIAGEM { get; set; }
        public System.DateTime DT_RESUMO { get; set; }
        public string ID_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public string CD_SUB_GRUPO { get; set; }
        public string DS_SUB_GRUPO { get; set; }
        public int QT_RPA { get; set; }
        public int QT_RPT_REPARO { get; set; }
        public int QT_TOTAL { get; set; }
    }
}
