//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AGRUPAMENTO_TIPO_PRODUTO
    {
        public TB_AGRUPAMENTO_TIPO_PRODUTO()
        {
            this.RL_AGRUPAMENTO_TIPOS_PRODUTO = new HashSet<RL_AGRUPAMENTO_TIPOS_PRODUTO>();
            this.TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO = new HashSet<TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO>();
            this.TB_REL_ACOMPANHAMENTO_PRODUCAO = new HashSet<TB_REL_ACOMPANHAMENTO_PRODUCAO>();
        }
    
        public int ID_AGRUPAMENTO { get; set; }
        public string DS_AGRUPAMENTO { get; set; }
    
        public virtual ICollection<RL_AGRUPAMENTO_TIPOS_PRODUTO> RL_AGRUPAMENTO_TIPOS_PRODUTO { get; set; }
        public virtual ICollection<TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO> TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO { get; set; }
        public virtual ICollection<TB_REL_ACOMPANHAMENTO_PRODUCAO> TB_REL_ACOMPANHAMENTO_PRODUCAO { get; set; }
    }
}
