//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPOSITO_CD
    {
        public TB_DEPOSITO_CD()
        {
            this.TB_REL_CADEIA_SUPRIMENTOS = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_SAIDA_INSUMOS = new HashSet<TB_REL_SAIDA_INSUMOS>();
            this.TB_REL_SAIDA_PRODUCAO = new HashSet<TB_REL_SAIDA_PRODUCAO>();
        }
    
        public int ID_CD { get; set; }
        public int ID_DEPOSITO { get; set; }
    
        public virtual TB_DEPOSITO TB_DEPOSITO { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS { get; set; }
        public virtual ICollection<TB_REL_SAIDA_INSUMOS> TB_REL_SAIDA_INSUMOS { get; set; }
        public virtual ICollection<TB_REL_SAIDA_PRODUCAO> TB_REL_SAIDA_PRODUCAO { get; set; }
    }
}
