//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DEPOSITO
    {
        public TB_DEPOSITO()
        {
            this.TB_CONFIG_GERAIS = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_DEPOSITO_CD = new HashSet<TB_DEPOSITO_CD>();
            this.TB_PROGRAMACAO_RECEBIMENTO = new HashSet<TB_PROGRAMACAO_RECEBIMENTO>();
            this.TB_SALDO_ESTOQUE = new HashSet<TB_SALDO_ESTOQUE>();
        }
    
        public int ID_DEPOSITO { get; set; }
        public string DS_DEPOSITO { get; set; }
    
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS { get; set; }
        public virtual ICollection<TB_DEPOSITO_CD> TB_DEPOSITO_CD { get; set; }
        public virtual ICollection<TB_PROGRAMACAO_RECEBIMENTO> TB_PROGRAMACAO_RECEBIMENTO { get; set; }
        public virtual ICollection<TB_SALDO_ESTOQUE> TB_SALDO_ESTOQUE { get; set; }
    }
}
