//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTRUTURA_TIPO_PRODUTO
    {
        public int ID_TIPO_PRODUTO { get; set; }
        public int ID_ESTRUTURA { get; set; }
        public int ID_INSUMO { get; set; }
        public int NR_NIVEL { get; set; }
        public Nullable<int> ID_INSUMO_PAI { get; set; }
        public int QT_INSUMO { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO1 { get; set; }
        public virtual TB_TIPO_PRODUTO TB_TIPO_PRODUTO { get; set; }
    }
}
