//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GRUPO_PRODUTO
    {
        public TB_GRUPO_PRODUTO()
        {
            this.TB_CONFIG_GERAIS = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS1 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS2 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS3 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS4 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS5 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS6 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_PRODUTO_COMPATIVEL = new HashSet<TB_PRODUTO_COMPATIVEL>();
            this.TB_PRODUTO = new HashSet<TB_PRODUTO>();
        }
    
        public int ID_GRUPO_PRODUTO { get; set; }
        public string CD_GRUPO_PRODUTO { get; set; }
        public string DS_GRUPO_PRODUTO { get; set; }
    
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS1 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS2 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS3 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS4 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS5 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS6 { get; set; }
        public virtual ICollection<TB_PRODUTO_COMPATIVEL> TB_PRODUTO_COMPATIVEL { get; set; }
        public virtual ICollection<TB_PRODUTO> TB_PRODUTO { get; set; }
    }
}
