//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public TB_PRODUTO()
        {
            this.TB_ESTRUTURA_TIPO_PRODUTO = new HashSet<TB_ESTRUTURA_TIPO_PRODUTO>();
            this.TB_ESTRUTURA_TIPO_PRODUTO1 = new HashSet<TB_ESTRUTURA_TIPO_PRODUTO>();
            this.TB_PREVISAO_CONSUMO_PRODUCAO = new HashSet<TB_PREVISAO_CONSUMO_PRODUCAO>();
            this.TB_PRODUTO_COMPATIVEL = new HashSet<TB_PRODUTO_COMPATIVEL>();
            this.TB_PRODUTO_COMPATIVEL1 = new HashSet<TB_PRODUTO_COMPATIVEL>();
            this.TB_REL_CADEIA_SUPRIMENTOS = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS1 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS2 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS3 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS4 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS5 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_CADEIA_SUPRIMENTOS6 = new HashSet<TB_REL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_ENTRADA_INSUMOS = new HashSet<TB_REL_ENTRADA_INSUMOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS1 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS2 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS3 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS4 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS5 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERAL_CADEIA_SUPRIMENTOS6 = new HashSet<TB_REL_GERAL_CADEIA_SUPRIMENTOS>();
            this.TB_REL_GERENCIAL = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL1 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL2 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL3 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL4 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL5 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_GERENCIAL6 = new HashSet<TB_REL_GERENCIAL>();
            this.TB_REL_MOV_FORNEC_EXTERNO = new HashSet<TB_REL_MOV_FORNEC_EXTERNO>();
            this.TB_REL_RPT_GARANTIA = new HashSet<TB_REL_RPT_GARANTIA>();
            this.TB_REL_SAIDA_INSUMOS = new HashSet<TB_REL_SAIDA_INSUMOS>();
            this.TB_REL_SAIDA_PRODUCAO = new HashSet<TB_REL_SAIDA_PRODUCAO>();
            this.TB_SALDO_ESTOQUE = new HashSet<TB_SALDO_ESTOQUE>();
            this.TB_TIPO_PRODUTO = new HashSet<TB_TIPO_PRODUTO>();
        }
    
        public int ID_PRODUTO { get; set; }
        public string CD_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public int ID_GRUPO_PRODUTO { get; set; }
        public int ID_SUBGRUPO_PRODUTO { get; set; }
        public string CD_SAP { get; set; }
    
        public virtual ICollection<TB_ESTRUTURA_TIPO_PRODUTO> TB_ESTRUTURA_TIPO_PRODUTO { get; set; }
        public virtual ICollection<TB_ESTRUTURA_TIPO_PRODUTO> TB_ESTRUTURA_TIPO_PRODUTO1 { get; set; }
        public virtual TB_GRUPO_PRODUTO TB_GRUPO_PRODUTO { get; set; }
        public virtual ICollection<TB_PREVISAO_CONSUMO_PRODUCAO> TB_PREVISAO_CONSUMO_PRODUCAO { get; set; }
        public virtual ICollection<TB_PRODUTO_COMPATIVEL> TB_PRODUTO_COMPATIVEL { get; set; }
        public virtual ICollection<TB_PRODUTO_COMPATIVEL> TB_PRODUTO_COMPATIVEL1 { get; set; }
        public virtual TB_SUBGRUPO_PRODUTO TB_SUBGRUPO_PRODUTO { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS1 { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS2 { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS3 { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS4 { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS5 { get; set; }
        public virtual ICollection<TB_REL_CADEIA_SUPRIMENTOS> TB_REL_CADEIA_SUPRIMENTOS6 { get; set; }
        public virtual ICollection<TB_REL_ENTRADA_INSUMOS> TB_REL_ENTRADA_INSUMOS { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS1 { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS2 { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS3 { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS4 { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS5 { get; set; }
        public virtual ICollection<TB_REL_GERAL_CADEIA_SUPRIMENTOS> TB_REL_GERAL_CADEIA_SUPRIMENTOS6 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL1 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL2 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL3 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL4 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL5 { get; set; }
        public virtual ICollection<TB_REL_GERENCIAL> TB_REL_GERENCIAL6 { get; set; }
        public virtual ICollection<TB_REL_MOV_FORNEC_EXTERNO> TB_REL_MOV_FORNEC_EXTERNO { get; set; }
        public virtual ICollection<TB_REL_RPT_GARANTIA> TB_REL_RPT_GARANTIA { get; set; }
        public virtual ICollection<TB_REL_SAIDA_INSUMOS> TB_REL_SAIDA_INSUMOS { get; set; }
        public virtual ICollection<TB_REL_SAIDA_PRODUCAO> TB_REL_SAIDA_PRODUCAO { get; set; }
        public virtual ICollection<TB_SALDO_ESTOQUE> TB_SALDO_ESTOQUE { get; set; }
        public virtual TB_SITUACAO_PRODUTO TB_SITUACAO_PRODUTO { get; set; }
        public virtual ICollection<TB_TIPO_PRODUTO> TB_TIPO_PRODUTO { get; set; }
    }
}
