//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO_COMPATIVEL
    {
        public int ID_PRODUTO { get; set; }
        public int ID_GRUPO_PRODUTO { get; set; }
        public int ID_PRODUTO_COMPATIVEL { get; set; }
    
        public virtual TB_GRUPO_PRODUTO TB_GRUPO_PRODUTO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO1 { get; set; }
    }
}
