//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROGRAMACAO_PRODUCAO
    {
        public TB_PROGRAMACAO_PRODUCAO()
        {
            this.TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO = new HashSet<TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO>();
            this.TB_PREVISAO_CONSUMO_PRODUCAO = new HashSet<TB_PREVISAO_CONSUMO_PRODUCAO>();
        }
    
        public int ID_PROGRAMACAO { get; set; }
        public string DS_PROGRAMACAO { get; set; }
        public System.DateTime DT_VIGENCIA_INICIAL { get; set; }
        public System.DateTime DT_VIGENCIA_FINAL { get; set; }
        public int QT_DIAS_PREVISAO_PRODUCAO { get; set; }
        public bool FL_ABERTO { get; set; }
    
        public virtual ICollection<TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO> TB_AGRUPAMENTO_PROGRAMACAO_PRODUCAO { get; set; }
        public virtual ICollection<TB_PREVISAO_CONSUMO_PRODUCAO> TB_PREVISAO_CONSUMO_PRODUCAO { get; set; }
    }
}
