//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROGRAMACAO_RECEBIMENTO
    {
        public int ID_PROGRAMACAO { get; set; }
        public string CD_SAP { get; set; }
        public int QT_PROGRAMACAO { get; set; }
        public System.DateTime DT_PREVISAO_RECEBIMENTO { get; set; }
        public string NR_PEDIDO_COMPRA { get; set; }
        public int ID_DEPOSITO { get; set; }
    
        public virtual TB_DEPOSITO TB_DEPOSITO { get; set; }
    }
}
