//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REL_PC_UTILIZACAO
    {
        public long ID_REL_PC_UTILIZACAO { get; set; }
        public System.DateTime DT_MOVIMENTO { get; set; }
        public string ID_GRUPO { get; set; }
        public string DS_GRUPO { get; set; }
        public string ID_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public string CODIGO_SAP { get; set; }
        public int QT_PRODUTO { get; set; }
    }
}
