//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REL_GERENCIAL
    {
        public int ID_RELATORIO { get; set; }
        public System.DateTime DT_RELATORIO { get; set; }
        public int ID_PRODUTO_NPA { get; set; }
        public int ID_PRODUTO_RPA { get; set; }
        public int ID_PRODUTO_RPT_TRIAGEM { get; set; }
        public int ID_PRODUTO_RPT_REPARO { get; set; }
        public int ID_PRODUTO_TEC_DESCONTINUADA { get; set; }
        public int ID_PRODUTO_RPT_GARANTIA { get; set; }
        public int ID_PRODUTO_SUCATA { get; set; }
        public int QT_ESTOQUE_NPA { get; set; }
        public int QT_ESTOQUE_RPA { get; set; }
        public int QT_ESTOQUE_TRIAGEM { get; set; }
        public int QT_ESTOQUE_RPT_REPARO { get; set; }
        public int QT_ESTOQUE_TEC_DESCONTINUADA { get; set; }
        public int QT_ESTOQUE_RPT_GARANTIA { get; set; }
        public int QT_ESTOQUE_SUCATA { get; set; }
        public int QT_CONSUMO_DIARIO { get; set; }
        public int QT_DIAS_CONSUMO { get; set; }
        public int QT_SALDO_PRODUTIVO { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO1 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO2 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO3 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO4 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO5 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO6 { get; set; }
    }
}
