//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REL_GERAL_CADEIA_SUPRIMENTOS
    {
        public int ID_RESUMO { get; set; }
        public System.DateTime DT_RESUMO { get; set; }
        public int ID_PRODUTO_NPA { get; set; }
        public int ID_PRODUTO_RPA { get; set; }
        public int ID_PRODUTO_RPT_TRIAGEM { get; set; }
        public int ID_PRODUTO_RPT_REPARO { get; set; }
        public int ID_PRODUTO_TEC_DESCONTINUADA { get; set; }
        public int ID_PRODUTO_RPT_GARANTIA { get; set; }
        public int ID_PRODUTO_SUCATA { get; set; }
        public Nullable<int> QT_SALDO_WIP { get; set; }
        public Nullable<int> QT_CONSUMO_DIA { get; set; }
        public Nullable<int> QT_DIAS_COBERTURA { get; set; }
        public Nullable<int> QT_EMREC_NPA { get; set; }
        public Nullable<int> QT_EMREC_RPA { get; set; }
        public Nullable<int> QT_EMREC_RPT_TRIAGEM { get; set; }
        public Nullable<int> QT_EMREC_DESCONTINUADO { get; set; }
        public Nullable<int> QT_EMREC_SUCATA { get; set; }
        public Nullable<int> QT_SALDO_FORNECEDOR { get; set; }
        public Nullable<int> QT_SALDO_LABORATORIO { get; set; }
        public Nullable<int> QT_PROXIMA_ENTREGA { get; set; }
        public Nullable<System.DateTime> DT_PROXIMA_ENTREGA { get; set; }
        public Nullable<int> QT_GERAL_ENTREGA { get; set; }
        public Nullable<int> QT_TOTAL_NPA { get; set; }
        public Nullable<int> QT_TOTAL_RPA { get; set; }
        public Nullable<int> QT_TOTAL_RPT_TRIAGEM { get; set; }
        public Nullable<int> QT_TOTAL_RPT_GARANTIA { get; set; }
        public Nullable<int> QT_NECESSIDADE_SUPRIMENTOS { get; set; }
        public Nullable<int> QT_NECESSIDADE_TRIAGEM { get; set; }
        public Nullable<int> QT_NECESSIDADE_REPARO { get; set; }
        public Nullable<int> QT_NECESSIDADE_COMPRA { get; set; }
        public Nullable<int> QT_EMREC_RPT_REPARO { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO1 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO2 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO3 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO4 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO5 { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO6 { get; set; }
    }
}
