//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REL_ACOMPANHAMENTO_PRODUCAO
    {
        public int ID_RESUMO { get; set; }
        public System.DateTime DT_RESUMO { get; set; }
        public int ID_AGRUPAMENTO { get; set; }
        public int QT_PRODUCAO { get; set; }
    
        public virtual TB_AGRUPAMENTO_TIPO_PRODUTO TB_AGRUPAMENTO_TIPO_PRODUTO { get; set; }
    }
}
