//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SALDO_ETAPA_PROCESSO
    {
        public long ID_SALDO_ETAPA_PROCESSO { get; set; }
        public System.DateTime DT_RELATORIO { get; set; }
        public int ID_DEPOSITO { get; set; }
        public string DS_DEPOSITO { get; set; }
        public int ID_LOCAL_ESTOQUE { get; set; }
        public string DS_LOCAL_ESTOQUE { get; set; }
        public string ID_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public string CODIGO_SAP { get; set; }
        public string ID_GRUPO { get; set; }
        public string DS_GRUPO { get; set; }
        public int ID_PROCESSO { get; set; }
        public string DS_PROCESSO { get; set; }
        public int ID_STATUS_CAIXA { get; set; }
        public string DS_STATUS_CAIXA { get; set; }
        public int QT_ITENS { get; set; }
    }
}
