//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SEMAFORO_COBERTURA_ESTOQUE
    {
        public int ID_SEMAFORO { get; set; }
        public int ID_SUBGRUPO_PRODUTO { get; set; }
        public int QT_ESTOQUE_BAIXO { get; set; }
        public int QT_ESTOQUE_ALERTA { get; set; }
        public int QT_ESTOQUE_IDEAL { get; set; }
    
        public virtual TB_SUBGRUPO_PRODUTO TB_SUBGRUPO_PRODUTO { get; set; }
    }
}
