//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SITUACAO_PRODUTO
    {
        public int ID_PRODUTO { get; set; }
        public bool FL_ATIVO { get; set; }
        public bool FL_CALCULO_AUTOMATICO_TRIAGEM { get; set; }
        public Nullable<float> PC_RECUPERACAO_TRIAGEM { get; set; }
    
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
    }
}
