//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SUBGRUPO_PRODUTO
    {
        public TB_SUBGRUPO_PRODUTO()
        {
            this.TB_PRODUTO = new HashSet<TB_PRODUTO>();
            this.TB_SEMAFORO_COBERTURA_ESTOQUE = new HashSet<TB_SEMAFORO_COBERTURA_ESTOQUE>();
        }
    
        public int ID_SUBGRUPO_PRODUTO { get; set; }
        public string CD_SUBGRUPO_PRODUTO { get; set; }
        public string DS_SUBGRUPO_PRODUTO { get; set; }
    
        public virtual ICollection<TB_PRODUTO> TB_PRODUTO { get; set; }
        public virtual ICollection<TB_SEMAFORO_COBERTURA_ESTOQUE> TB_SEMAFORO_COBERTURA_ESTOQUE { get; set; }
    }
}
