//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SALDO_ESTOQUE
    {
        public int ID_SALDO_ESTOQUE { get; set; }
        public System.DateTime DT_SALDO_ESTOQUE { get; set; }
        public int ID_DEPOSITO { get; set; }
        public int ID_PRODUTO { get; set; }
        public double QT_PRODUTO { get; set; }
        public int ID_LOCAL_ESTOQUE { get; set; }
    
        public virtual TB_DEPOSITO TB_DEPOSITO { get; set; }
        public virtual TB_PRODUTO TB_PRODUTO { get; set; }
    }
}
