//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCADPRO
    {
        public ESCADPRO()
        {
            this.TB_PREC_REC_ITEM = new HashSet<TB_PREC_REC_ITEM>();
        }
    
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public string NUM_DESENHO { get; set; }
        public Nullable<System.DateTime> DATA_DESENHO { get; set; }
        public string GRUPO { get; set; }
        public string SUB_GRUPO { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string COD_ESTRUTURA { get; set; }
        public string UNIDADE { get; set; }
        public Nullable<double> PESO_LIQUIDO { get; set; }
        public string SITUACAO { get; set; }
        public Nullable<double> ESTOQUE_MAXIMO { get; set; }
        public Nullable<double> ESTOQUE_MINIMO { get; set; }
        public string CLASSIFICACAO_FISCAL { get; set; }
        public Nullable<double> ALIQUOTA_IPI { get; set; }
        public string FLAG_RED_ICMS { get; set; }
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        public Nullable<System.DateTime> DATA_ALT { get; set; }
        public Nullable<System.DateTime> ULT_MOV { get; set; }
        public string FLAG_VALORIZA { get; set; }
        public string SITUACAO_INV { get; set; }
        public string FLAG_CRED_ICMS { get; set; }
        public string FLAG_CRED_IPI { get; set; }
        public Nullable<int> ORIGEM { get; set; }
        public string COD_ALTERNATIVO { get; set; }
        public Nullable<double> PRECO_PECA { get; set; }
        public Nullable<double> PRECO_VENDA { get; set; }
        public Nullable<double> MARGEM_LUCRO { get; set; }
        public Nullable<double> CUSTO_UNITARIO { get; set; }
        public Nullable<int> VERSAO_ATUAL { get; set; }
        public string UTILIZA_LOTE { get; set; }
        public string SOL_LOTE_FORN { get; set; }
        public string METODO_LOTE { get; set; }
        public string CHAVE_METODO { get; set; }
        public string DEF_LOTE_ENT { get; set; }
        public Nullable<int> NUM_LOTE_ENT { get; set; }
        public string DEF_LOTE_INV { get; set; }
        public Nullable<int> NUM_LOTE_INV { get; set; }
        public string SITUACAO_LOTE { get; set; }
        public Nullable<double> QTDE_CAIXA { get; set; }
        public Nullable<double> QTDE_PALLET { get; set; }
        public string REDUZIDO { get; set; }
        public string DESCRICAO_FAT { get; set; }
        public string CLASSIFICACAO_ITEM { get; set; }
        public Nullable<double> GRAMATURA { get; set; }
        public string TIPO_ONDA { get; set; }
        public Nullable<double> TEMPO_PREP { get; set; }
        public Nullable<double> TEMPO_OPER { get; set; }
        public Nullable<double> TEMPO_MAQ { get; set; }
        public Nullable<double> TEMPO_FABR { get; set; }
        public Nullable<double> QTDE_BASE { get; set; }
        public Nullable<double> DIAGONAL_MENOR { get; set; }
        public Nullable<double> DIAGONAL_MAIOR { get; set; }
        public Nullable<double> ESPESSURA { get; set; }
        public Nullable<double> CORDAO { get; set; }
        public string FLAG_CRED_PIS { get; set; }
        public string FLAG_CRED_COFINS { get; set; }
        public Nullable<double> TOLER_MENOR { get; set; }
        public Nullable<double> TOLER_MAIOR { get; set; }
        public string SENHA_CAD { get; set; }
        public string SENHA_ALT { get; set; }
        public Nullable<int> ANALISE_FIS_QUI { get; set; }
        public Nullable<int> ANALISE_MICROBI { get; set; }
        public string CODIGO_EAN_UCC { get; set; }
        public Nullable<double> QTDE_FRACIONADA { get; set; }
        public string FLAG_DESTAQUE_IPI { get; set; }
        public string PADRAO_LOTE { get; set; }
        public string FLAG_VERSAO { get; set; }
        public string FLAG_FICHA { get; set; }
        public Nullable<int> EMBALAGEM_PADRAO { get; set; }
        public string EXCECAO_NCM { get; set; }
        public string GENERO { get; set; }
        public string COD_SERVICO { get; set; }
        public Nullable<double> ALIQUOTA_ISS { get; set; }
        public Nullable<int> ULT_RG_VISANET_RFI { get; set; }
        public Nullable<int> ULT_RG_VISANET_LEG { get; set; }
        public Nullable<int> ULT_VISANET_PROV { get; set; }
        public string FABRICANTE { get; set; }
        public string SUCATA { get; set; }
        public string NPA { get; set; }
        public string RPA { get; set; }
        public string RPT_TRIAGEM { get; set; }
        public string RPT_REPARO { get; set; }
        public string TECN_DESCONTIN { get; set; }
        public Nullable<int> CAPACIDADE_VOLUME { get; set; }
        public string CODIGO_SAP { get; set; }
        public string RPT_GARANTIA { get; set; }
    
        public virtual ICollection<TB_PREC_REC_ITEM> TB_PREC_REC_ITEM { get; set; }
    }
}
