//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAIXA
    {
        public TB_CAIXA()
        {
            this.TB_INVENTARIO_DESMEMB = new HashSet<TB_INVENTARIO_DESMEMB>();
            this.TB_INVENTARIO_DESMEMB1 = new HashSet<TB_INVENTARIO_DESMEMB>();
            this.TB_ITENS_INVENTARIO = new HashSet<TB_ITENS_INVENTARIO>();
        }
    
        public int ID_CAIXA { get; set; }
        public Nullable<int> ID_FASE { get; set; }
        public Nullable<int> ID_PRE_REC_ITEM { get; set; }
        public Nullable<int> ID_STATUS_CAIXA { get; set; }
        public Nullable<int> QT_ITENS { get; set; }
        public string NR_ETIQUETA { get; set; }
        public Nullable<int> QT_CONT_CQ { get; set; }
        public string FL_IMPRESSO { get; set; }
        public Nullable<int> QT_CONT_REC { get; set; }
        public Nullable<int> ID_MOTIVO_RECUSA { get; set; }
        public Nullable<int> ID_LOCACAO_LOCAL { get; set; }
    
        public virtual ICollection<TB_INVENTARIO_DESMEMB> TB_INVENTARIO_DESMEMB { get; set; }
        public virtual ICollection<TB_INVENTARIO_DESMEMB> TB_INVENTARIO_DESMEMB1 { get; set; }
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO { get; set; }
        public virtual TB_PREC_REC_ITEM TB_PREC_REC_ITEM { get; set; }
    }
}
