//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITENS_INVENTARIO
    {
        public int ID_ITEM_INVENTARIO { get; set; }
        public Nullable<int> ID_INVENTARIO { get; set; }
        public string ID_GRUPO { get; set; }
        public Nullable<int> ID_LOCAL_ESTOQUE { get; set; }
        public Nullable<int> ID_CAIXA { get; set; }
        public Nullable<int> QT_ITENS { get; set; }
        public Nullable<int> ID_STATUS_ITEM_INVENTARIO { get; set; }
        public Nullable<System.DateTime> DT_HR_P_CONTAGEM { get; set; }
        public Nullable<int> ID_USR_TORRE_P_CONTAGEM { get; set; }
        public Nullable<int> QT_P_CONTAGEM { get; set; }
        public Nullable<System.DateTime> DT_HR_S_CONTAGEM { get; set; }
        public Nullable<int> ID_USR_TORRE_S_CONTAGEM { get; set; }
        public Nullable<int> QT_S_CONTAGEM { get; set; }
        public Nullable<System.DateTime> DT_HR_T_CONTAGEM { get; set; }
        public Nullable<int> ID_USR_TORRE_T_CONTAGEM { get; set; }
        public Nullable<int> QT_T_CONTAGEM { get; set; }
        public Nullable<int> ID_DEPOSITO { get; set; }
        public string ID_SUBGRUPO { get; set; }
        public Nullable<int> ID_STATUS_CAIXA { get; set; }
        public Nullable<System.DateTime> DT_HR_P_BIPAGEM { get; set; }
    
        public virtual TB_INVENTARIO TB_INVENTARIO { get; set; }
        public virtual TB_CAIXA TB_CAIXA { get; set; }
        public virtual TB_TORRE_USR_INVENTARIO TB_TORRE_USR_INVENTARIO { get; set; }
        public virtual TB_TORRE_USR_INVENTARIO TB_TORRE_USR_INVENTARIO1 { get; set; }
        public virtual TB_TORRE_USR_INVENTARIO TB_TORRE_USR_INVENTARIO2 { get; set; }
        public virtual TB_STATUS_ITEM_INVENTARIO TB_STATUS_ITEM_INVENTARIO { get; set; }
    }
}
