//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_INVENTARIO
    {
        public TB_INVENTARIO()
        {
            this.TB_INVENTARIO_DESMEMB = new HashSet<TB_INVENTARIO_DESMEMB>();
            this.TB_ITENS_INVENTARIO = new HashSet<TB_ITENS_INVENTARIO>();
            this.TB_TORRE_USR_INVENTARIO = new HashSet<TB_TORRE_USR_INVENTARIO>();
        }
    
        public int ID_INVENTARIO { get; set; }
        public Nullable<System.DateTime> DT_INVENTARIO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_STATUS_INVENTARIO { get; set; }
        public Nullable<System.DateTime> DT_INICIO { get; set; }
        public Nullable<System.DateTime> DT_ENCERRAMENTO { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<int> NR_INTERVALO_CX_PARADA { get; set; }
        public Nullable<int> NR_TEMPO_CX_PARADA { get; set; }
        public string DS_EMAIL_CX_PARADA { get; set; }
    
        public virtual ICollection<TB_INVENTARIO_DESMEMB> TB_INVENTARIO_DESMEMB { get; set; }
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO { get; set; }
        public virtual ICollection<TB_TORRE_USR_INVENTARIO> TB_TORRE_USR_INVENTARIO { get; set; }
    }
}
