//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STATUS_ITEM_INVENTARIO
    {
        public TB_STATUS_ITEM_INVENTARIO()
        {
            this.TB_ITENS_INVENTARIO = new HashSet<TB_ITENS_INVENTARIO>();
        }
    
        public int ID_STATUS_ITEM_INVENTARIO { get; set; }
        public string DS_STATUS_ITEM_INVENTARIO { get; set; }
    
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO { get; set; }
    }
}
