//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TORRE_USR_INVENTARIO
    {
        public TB_TORRE_USR_INVENTARIO()
        {
            this.TB_ITENS_INVENTARIO = new HashSet<TB_ITENS_INVENTARIO>();
            this.TB_ITENS_INVENTARIO1 = new HashSet<TB_ITENS_INVENTARIO>();
            this.TB_ITENS_INVENTARIO2 = new HashSet<TB_ITENS_INVENTARIO>();
        }
    
        public int ID_USR_TORRE_INVENTARIO { get; set; }
        public int ID_INVENTARIO { get; set; }
        public int ID_TORRE { get; set; }
        public int ID_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_HR_INICIO { get; set; }
        public Nullable<System.DateTime> DT_HR_FINAL { get; set; }
    
        public virtual TB_INVENTARIO TB_INVENTARIO { get; set; }
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO { get; set; }
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO1 { get; set; }
        public virtual ICollection<TB_ITENS_INVENTARIO> TB_ITENS_INVENTARIO2 { get; set; }
        public virtual TB_TORRE_INVENTARIO TB_TORRE_INVENTARIO { get; set; }
    }
}
