//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TORRE_INVENTARIO
    {
        public TB_TORRE_INVENTARIO()
        {
            this.TB_TORRE_USR_INVENTARIO = new HashSet<TB_TORRE_USR_INVENTARIO>();
        }
    
        public int ID_TORRE_INVENTARIO { get; set; }
        public string DS_TORRE_INVENTARIO { get; set; }
        public string FL_ATIVO { get; set; }
        public string FL_REALIZA_T_CONTAGEM { get; set; }
    
        public virtual ICollection<TB_TORRE_USR_INVENTARIO> TB_TORRE_USR_INVENTARIO { get; set; }
    }
}
