//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventarioCxParadaService.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NM_USUARIO { get; set; }
        public string DS_LOGIN { get; set; }
        public string DS_SENHA { get; set; }
        public string FL_ADMIN { get; set; }
        public string FL_INVENTARIO { get; set; }
        public Nullable<int> ID_DEPOSITO { get; set; }
        public Nullable<int> ID_TORRE { get; set; }
    }
}
