//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESGRUPRO
    {
        public ESGRUPRO()
        {
            this.TB_CONFIG_GERAIS = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS1 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS2 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS3 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS4 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS5 = new HashSet<TB_CONFIG_GERAIS>();
            this.TB_CONFIG_GERAIS6 = new HashSet<TB_CONFIG_GERAIS>();
        }
    
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        public Nullable<System.DateTime> DATA_ALT { get; set; }
        public Nullable<int> COD_ESTAB { get; set; }
    
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS1 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS2 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS3 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS4 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS5 { get; set; }
        public virtual ICollection<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS6 { get; set; }
    }
}
