//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESSUBPRO
    {
        public string CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        public Nullable<System.DateTime> DATA_ALT { get; set; }
        public Nullable<int> COD_ESTAB { get; set; }
    }
}
