//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirebirdEntities : DbContext
    {
        public FirebirdEntities()
            : base("name=FirebirdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ESCADDEP> ESCADDEP { get; set; }
        public DbSet<ESCADPRO> ESCADPRO { get; set; }
        public DbSet<ESGRUPRO> ESGRUPRO { get; set; }
        public DbSet<ESSUBPRO> ESSUBPRO { get; set; }
        public DbSet<TB_CONFIG_GERAIS> TB_CONFIG_GERAIS { get; set; }
        public DbSet<PCESTPRO_H> PCESTPRO_H { get; set; }
        public DbSet<PCESTPRO_I> PCESTPRO_I { get; set; }
        public DbSet<TB_PRE_REC> TB_PRE_REC { get; set; }
        public DbSet<TB_PREC_REC_ITEM> TB_PREC_REC_ITEM { get; set; }
    }
}
