//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCESTPRO_H
    {
        public int ESTRUT_ID { get; set; }
        public string COD_ITEM { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> VERSAO { get; set; }
        public Nullable<System.DateTime> DT_INICIO { get; set; }
        public Nullable<System.DateTime> DT_TERMINO { get; set; }
        public string USUARIO { get; set; }
    }
}
