//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCESTPRO_I
    {
        public int ESTRUT_ID { get; set; }
        public int ITEM_ID { get; set; }
        public string INSUMO { get; set; }
        public int NIVEL { get; set; }
        public string INSUMO_PAI { get; set; }
        public Nullable<int> QTDE { get; set; }
        public string EXPLAB { get; set; }
        public string LIBERAINSUMO { get; set; }
    }
}
