//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONFIG_GERAIS
    {
        public int ID_CONFIG { get; set; }
        public string DS_PASTA_NF_RECEBIMENTO { get; set; }
        public string FL_ANEXA_NF_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<int> ID_USER_INC { get; set; }
        public Nullable<System.DateTime> DT_ULT_ALTERACAO { get; set; }
        public Nullable<int> ID_USER_ULT_ALT { get; set; }
        public Nullable<int> ID_RECUSA_DIV_QUANTIDADE_REC { get; set; }
        public string ID_GRUPO_RPA { get; set; }
        public string ID_GRUPO_TRIAGEM { get; set; }
        public string ID_GRUPO_TEC_DESCONTINUADA { get; set; }
        public string ID_GRUPO_NPA { get; set; }
        public string ID_GRUPO_RPT_REPARO { get; set; }
        public Nullable<int> TP_SEPARACAO { get; set; }
        public Nullable<int> ID_LOCAL_DEP_CONTROLADO { get; set; }
        public string ID_GRUPO_SUCATA { get; set; }
        public string ID_GRUPO_RPT_GARANTIA { get; set; }
    
        public virtual ESGRUPRO ESGRUPRO { get; set; }
        public virtual ESGRUPRO ESGRUPRO1 { get; set; }
        public virtual ESGRUPRO ESGRUPRO2 { get; set; }
        public virtual ESGRUPRO ESGRUPRO3 { get; set; }
        public virtual ESGRUPRO ESGRUPRO4 { get; set; }
        public virtual ESGRUPRO ESGRUPRO5 { get; set; }
        public virtual ESGRUPRO ESGRUPRO6 { get; set; }
    }
}
