//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PREC_REC_ITEM
    {
        public int ID_PRE_REC_ITEM { get; set; }
        public Nullable<int> ID_PRE_REC { get; set; }
        public Nullable<decimal> QT_VOLUME { get; set; }
        public Nullable<decimal> QT_UNIDADE_VOLUME { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<int> ID_USER_INC { get; set; }
        public Nullable<System.DateTime> ID_ULT_ALTERACAO { get; set; }
        public Nullable<int> ID_USER_ULT_ALT { get; set; }
        public string ID_ITEM_YEP { get; set; }
        public Nullable<int> ID_INSPEC { get; set; }
        public Nullable<int> QT_REJEICAO { get; set; }
        public string FL_TESTE_FUNC_RAPIDO { get; set; }
        public string FL_TESTE_EXAME_VISUAL { get; set; }
        public string DS_OBSERVACAO { get; set; }
    
        public virtual ESCADPRO ESCADPRO { get; set; }
        public virtual TB_PRE_REC TB_PRE_REC { get; set; }
    }
}
