//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSupplyChain.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRE_REC
    {
        public TB_PRE_REC()
        {
            this.TB_PREC_REC_ITEM = new HashSet<TB_PREC_REC_ITEM>();
        }
    
        public int ID_PRE_REC { get; set; }
        public string NR_NOTA_FISCAL { get; set; }
        public string NR_SERIE { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_NF { get; set; }
        public Nullable<int> ID_DEPOSITO_ORIGEM { get; set; }
        public string DS_CAMINHO_NF { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<int> ID_USER_INC { get; set; }
        public Nullable<System.DateTime> DT_ULT_ALTERACAO { get; set; }
        public Nullable<int> ID_USER_ULT_ALT { get; set; }
        public Nullable<int> ST_PRE_REC { get; set; }
        public Nullable<int> ID_DEPOSITO_DESTINO { get; set; }
        public Nullable<int> ID_MOTIVO_RECUSA { get; set; }
        public Nullable<int> ID_FLUXO { get; set; }
        public Nullable<int> ID_TIPO_PRE_REC { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO { get; set; }
        public string NR_PEDIDO_COMPRA { get; set; }
        public Nullable<System.DateTime> DT_PEDIDO_COMPRA { get; set; }
        public string NR_NOTA_FISCAL_COMPRA { get; set; }
    
        public virtual ESCADDEP ESCADDEP { get; set; }
        public virtual ESCADDEP ESCADDEP1 { get; set; }
        public virtual ICollection<TB_PREC_REC_ITEM> TB_PREC_REC_ITEM { get; set; }
    }
}
